### PR TITLE
Done test

### PR DESCRIPTION
**Pull request by thacayaniban**

### CODE REVIEW

**Comment by avana-sky** [comment]
@thacayaniban thank you for your PR. Please allow me two days to review it.

**Comment by avana-sky** [comment]
@thacayaniban The validation of empty space is not working. It suppose to have "Field_B should not contain any space".

screenshot 2019-02-20 at 12 14 56 pm

**Comment by thacayaniban** [comment]
i have fixed the excel file for the correct validation.. check

**Comment by avana-sky** [comment]
@thacayaniban sorry for the delayed response. I believe you were using the excel file we've provided. May I know is there any problem with the excel file?

**Comment by thacayaniban** [comment]
in the excel file u gave date format return no empty value.. so that validation is not working.. i changed that to "1 1" with space returning value with space then its working

**Pull request closed without merging**
